### ISSUE TITLE
createNew naming convention

### ISSUE THREAD

**Issue by muichkine** [vuex-orm/plugin-change-flags#3]
Vuex-ORM differentiates Models `create` and `insert`.

I would say it is wise to respect that convention in the plugin-change-flags API as far as API coherence is concerned.

**Comment by tvillaren** [comment]
Hello @muichkine,

`createNew` is an addition to the initial API, thus its different name.

**Comment by muichkine** [comment]
Yes but the API seems different.

For instance. Model.create() in Vuex seems to be able to take a { data: { key: value }} as an input while seems not to.

I'm debugging my app, but for instance, when doing

```
 DocumentPrice.createNew({
        data: { DocDataId: 13 }
      }).then((entities) => { console.log(entities); });
```
the console output shows a DocDataId set to `null` which is puzzling me.

![image](https://user-images.githubusercontent.com/2428966/62863228-7c0b1580-bd08-11e9-90e9-6e236e2b0a39.png)
